baseurl = "https://carlogilmar.github.io/blog/"
languageCode = "en-us"
title = "@carlogilmar"
theme = "hugo-theme-bootstrap4-blog"
paginate = 5
copyright = "This blog was created in 2016 for share my experiencies, knowledge and learning experiences. <br> For any question please contact me here: carlogilmar12@gmail.com or just send me a tweet. <br> Thank you for visit my content. <br> <strong> Last updated: June, 2019.</strong>"
#
disqusShortname = "carlogilmar-github-io"
googleAnalytics="UA-90617617-1"

[permalinks]
post = "/:year/:month/:title/"
page = "/:slug/"


#[[menu.navbar]]
#  name = "Link 1"
#  url = "https://example.org"


# Theme variables
#
[params]
# Site author
author = "@carlogilmar"

# Description/subtitle for homepage (can be Markdown)
description = "<small>Blog for share my learning experience as software developer since 2016.</small>"

# Show header (default: true)
#header_visible = true

# Format dates with Go's time formatting
date_format = "Mon Jan 02, 2006"

# verification string for Google Webmaster Tools
#google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

# Optionally display a message about the site's use of cookies, which may be
# required for your site in the European Union. Set the parameter below to a
# page where the user can get more information about cookies, either on your
# site or externally, for example:
#cookie_consent_info_url = "/cookie-information/"
#cookie_consent_info_url = "http://cookiesandyou.com"

# show sharing icons on pages/posts (default: true)
#sharingicons = true

# Display post summaries instead of content in list templates (default: true)
#truncate = true

# Disable the use of sub-resource integrity on CSS/JS assets (default: false)
# Useful if you're using a CDN or other host where you can't control cache headers
#disable_sri = false

[params.sidebar]
# Optional about block for sidebar (can be Markdown)
about = ""

# How many posts to show on the sidebar (Default: 5)
#num_recent_posts = 2

[params.social]
# Optional, used for attribution in Twitter cards (ideally not a person
# for example: nytimes, flickr, NatGeo, etc).
# See: https://dev.twitter.com/cards/types/summary-large-image
twitter = "carlogilmar"

